### PR TITLE
Fix web authentication scopes

### LINKED ISSUE #87: Authentication scopes for web are hardcoded
Currently for the web implementation the scopes are hardcoded within `spotify_sdk_web.dart`:

```
/// spotify auth scopes
  static const List<String> authenticationScopes = [
    'streaming',
    'user-read-email',
    'user-read-private',
    'app-remote-control',
    'user-modify-playback-state',
    'playlist-read-private',
    'playlist-modify-public',
    'user-read-currently-playing'
  ];
```

We should be taking them from `SpotifySdk.getAuthenticationToken` or `connectToSpotifyRemote `.

### PR DESCRIPTION
**Pull request by itsMatoosh**
The web implementation will now use the authentication scopes supplied by the user in methods `SpotifySdk.connectToSpotifyRemote` and `SpotifySdk.getAuthenticationToken`. Removed hardcoded scopes. If the supplied scope is null, the implementation will use [the minimal list of scopes](https://developer.spotify.com/documentation/web-playback-sdk/quick-start/) that are required for the web player to work.

Fixes #87

### CODE REVIEW

File: lib/spotify_sdk_web.dart [hunk 1]
```diff
@@ -150,20 +142,15 @@ class SpotifySdkPlugin {
           return true;
         }
         log('Connecting to Spotify...');
-        // update the client id and redirect url
-        var clientId = call.arguments[ParamNames.clientId] as String?;
-        var redirectUrl = call.arguments[ParamNames.redirectUrl] as String?;
+        var clientId = call.arguments[ParamNames.clientId] as String;
+        var redirectUrl = call.arguments[ParamNames.redirectUrl] as String;
```
Comment (fotiDim) [inline lib/spotify_sdk_web.dart:146]: If I am not mistaken casting can fail so it better to leave it as nullable.

File: lib/spotify_sdk_web.dart [hunk 2]
```diff
@@ -150,20 +142,15 @@ class SpotifySdkPlugin {
...
-                  'Client id or redirectUrl are not set or have invalid format',
-              code: 'Authentication Error');
-        }
+        var scopes =
+            call.arguments[ParamNames.scope] as String? ?? DEFAULT_SCOPE;
 
         // get initial token
-        await _authorizeSpotify(clientId: clientId!, redirectUrl: redirectUrl!);
+        await _authorizeSpotify(
+            clientId: clientId, redirectUrl: redirectUrl, scopes: scopes);
```
Comment (fotiDim) [inline lib/spotify_sdk_web.dart:153]: Is it better to be defensive here and if clientId and redirectUrl then not call `_authorizeSpotify` and perhaps throw an exception

File: lib/spotify_sdk_web.dart [hunk 3]
```diff
@@ -197,7 +184,9 @@ class SpotifySdkPlugin {
       case MethodNames.getAuthenticationToken:
         return await _authorizeSpotify(
             clientId: call.arguments[ParamNames.clientId] as String,
-            redirectUrl: call.arguments[ParamNames.redirectUrl] as String);
+            redirectUrl: call.arguments[ParamNames.redirectUrl] as String,
```
Comment (fotiDim) [inline lib/spotify_sdk_web.dart:187]: Same as above

File: lib/spotify_sdk_web.dart [hunk 4]
```diff
@@ -197,7 +184,9 @@ class SpotifySdkPlugin {
...
+            scopes:
+                call.arguments[ParamNames.scope] as String? ?? DEFAULT_SCOPE);
```
Comment (fotiDim) [inline lib/spotify_sdk_web.dart:189]: I think that also works
```suggestion
                call.arguments[ParamNames.scope] as String ?? DEFAULT_SCOPE);
```

File: lib/spotify_sdk_web.dart [hunk 5]
```diff
@@ -91,6 +79,10 @@ class SpotifySdkPlugin {
   /// Lock for getting the token
   final synchronized.Lock _getTokenLock = synchronized.Lock(reentrant: true);
 
+  /// Default scopes that are required for Web SDK to work
+  static const String DEFAULT_SCOPE =
```
Comment (fotiDim) [inline lib/spotify_sdk_web.dart:83]:
```suggestion
  static const String DEFAULT_SCOPES =
```

**Comment by fotiDim** [comment]
Some small things could be improved.
A general suggestion, perhaps for another PR is to use explicit variable types (String, String?, bool etc.) instead of `var`.  `spotify_sdk.dart` in its majority uses them.

**Comment by fotiDim** [comment]
Also please state this fix in the changelog under `2.1.0`.

**Comment by itsMatoosh** [comment]
@fotiDim This should be now all resolved. Sorry for the delay, I was having important uni exams.

File: lib/spotify_sdk_web.dart [hunk 6]
```diff
@@ -195,9 +191,23 @@ class SpotifySdkPlugin {
           return false;
         }
       case MethodNames.getAuthenticationToken:
+        var clientId = call.arguments[ParamNames.clientId] as String?;
+        var redirectUrl = call.arguments[ParamNames.redirectUrl] as String?;
+
+        // ensure that required arguments are present
+        if (!(clientId?.isNotEmpty == true &&
+            redirectUrl?.isNotEmpty == true)) {
```
Comment (fotiDim) [inline lib/spotify_sdk_web.dart:199]:
```suggestion
        if (clientId == null ||
            clientId.isEmpty ||
            redirectUrl == null ||
            redirectUrl.isEmpty) {
```


Better do it this way. This will allow you to remove the forced unwrapping down below.

File: lib/spotify_sdk_web.dart [hunk 7]
```diff
@@ -195,9 +191,23 @@ class SpotifySdkPlugin {
...
+              message:
+                  'Client id or redirectUrl are not set or have invalid format',
+              code: 'Authentication Error');
+        }
+
         return await _authorizeSpotify(
-            clientId: call.arguments[ParamNames.clientId] as String,
-            redirectUrl: call.arguments[ParamNames.redirectUrl] as String);
+            clientId: clientId!,
+            redirectUrl: redirectUrl!,
```
Comment (fotiDim) [inline lib/spotify_sdk_web.dart:208]:
```suggestion
            clientId: clientId,
            redirectUrl: redirectUrl,
```

File: lib/spotify_sdk_web.dart [hunk 8]
```diff
@@ -163,7 +158,8 @@ class SpotifySdkPlugin {
         }
 
         // get initial token
-        await _authorizeSpotify(clientId: clientId!, redirectUrl: redirectUrl!);
+        await _authorizeSpotify(
+            clientId: clientId!, redirectUrl: redirectUrl!, scopes: scopes);
```
Comment (fotiDim) [inline lib/spotify_sdk_web.dart:162]:
```suggestion
            clientId: clientId, redirectUrl: redirectUrl, scopes: scopes);
```

File: lib/spotify_sdk_web.dart [hunk 9]
```diff
@@ -150,10 +142,13 @@ class SpotifySdkPlugin {
...
-        // update the client id and redirect url
         var clientId = call.arguments[ParamNames.clientId] as String?;
         var redirectUrl = call.arguments[ParamNames.redirectUrl] as String?;
         var playerName = call.arguments[ParamNames.playerName] as String?;
+        var scopes =
+            call.arguments[ParamNames.scope] as String? ?? DEFAULT_SCOPES;
+
+        // ensure that required arguments are present
         if (!(clientId?.isNotEmpty == true &&
             redirectUrl?.isNotEmpty == true)) {
```
Comment (fotiDim) [inline lib/spotify_sdk_web.dart:153]: Better change that one as the one below.

Comment (itsMatoosh) [reply lib/spotify_sdk_web.dart]: I see, that is indeed much better, I made the changes now.

**Review by fotiDim — APPROVED** [review]
Thank you for the changes. Looks good! 😎
